[package]
name = "organize-photo-zip"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "2.2"
kamadak-exif = "0.5"
chrono = "0.4"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
regex = "1.10"

[dev-dependencies]
mockall = "0.13"
